/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./src/**/*.{html,ts}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Nunito", "ui-sans-serif", "system-ui", "-apple-system", "Segoe UI", "sans-serif"],
        display: ["Nunito", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        success: { DEFAULT: "hsl(var(--success))", foreground: "hsl(var(--success-foreground))" },
        warning: { DEFAULT: "hsl(var(--warning))", foreground: "hsl(var(--warning-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xl: "calc(var(--radius) + 4px)",
        "2xl": "calc(var(--radius) + 8px)",
      },
      backgroundImage: {
        "gradient-primary": "linear-gradient(135deg, hsl(var(--primary)) 0%, hsl(var(--secondary)) 100%)",
        "gradient-primary-soft": "linear-gradient(135deg, hsl(var(--primary) / 0.14) 0%, hsl(var(--secondary) / 0.14) 100%)",
        "gradient-card": "linear-gradient(180deg, hsl(var(--card)) 0%, hsl(var(--card) / 0.72) 100%)",
        "mesh-gradient": "radial-gradient(at 15% 15%, hsl(var(--gradient-start) / 0.16) 0px, transparent 55%), radial-gradient(at 85% 5%, hsl(var(--secondary) / 0.13) 0px, transparent 50%), radial-gradient(at 80% 85%, hsl(var(--gradient-end) / 0.14) 0px, transparent 55%), radial-gradient(at 10% 90%, hsl(var(--secondary) / 0.10) 0px, transparent 50%)",
        "gradient-shine": "linear-gradient(110deg, transparent 25%, hsl(var(--primary-foreground) / 0.25) 45%, transparent 65%)",
      },
      boxShadow: {
        glow: "0 0 24px hsl(var(--glow-color) / 0.35)",
        "glow-lg": "0 0 48px hsl(var(--glow-color) / 0.45)",
        soft: "0 2px 12px hsl(28 30% 12% / 0.06)",
        card: "0 4px 24px hsl(28 30% 12% / 0.07)",
        "card-hover": "0 12px 32px hsl(28 30% 12% / 0.12)",
      },
      keyframes: {
        "fade-in": { from: { opacity: "0" }, to: { opacity: "1" } },
        "fade-in-up": { from: { opacity: "0", transform: "translateY(16px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "scale-in": { from: { opacity: "0", transform: "scale(0.95)" }, to: { opacity: "1", transform: "scale(1)" } },
        "slide-in-right": { from: { transform: "translateX(100%)" }, to: { transform: "translateX(0)" } },
        "slide-in-left": { from: { transform: "translateX(-100%)" }, to: { transform: "translateX(0)" } },
        "slide-up": { from: { transform: "translateY(100%)" }, to: { transform: "translateY(0)" } },
        "pulse-subtle": { "0%, 100%": { transform: "scale(1)", opacity: "1" }, "50%": { transform: "scale(1.05)", opacity: "0.92" } },
        float: { "0%, 100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-8px)" } },
        glow: { "0%, 100%": { boxShadow: "0 0 20px hsl(var(--glow-color) / 0.25)" }, "50%": { boxShadow: "0 0 36px hsl(var(--glow-color) / 0.5)" } },
        shimmer: { from: { backgroundPosition: "-200% 0" }, to: { backgroundPosition: "200% 0" } },
        "bounce-soft": { "0%, 100%": { transform: "translateY(0)" }, "30%": { transform: "translateY(-6px)" }, "60%": { transform: "translateY(2px)" } },
        "confetti-fall": { "0%": { transform: "translateY(-10vh)", opacity: "1" }, "100%": { transform: "translateY(110vh)", opacity: "0.4" } },
        "confetti-spin": { from: { transform: "rotate(0deg)" }, to: { transform: "rotate(720deg)" } },
      },
      animation: {
        "fade-in": "fade-in 0.4s ease-out both",
        "fade-in-up": "fade-in-up 0.45s ease-out both",
        "scale-in": "scale-in 0.25s ease-out both",
        "slide-in-right": "slide-in-right 0.3s ease-out both",
        "slide-in-left": "slide-in-left 0.3s ease-out both",
        "slide-up": "slide-up 0.35s ease-out both",
        "pulse-subtle": "pulse-subtle 1.6s ease-in-out infinite",
        float: "float 6s ease-in-out infinite",
        glow: "glow 2.4s ease-in-out infinite",
        shimmer: "shimmer 1.8s linear infinite",
        "bounce-soft": "bounce-soft 0.7s ease-out",
        "confetti-fall": "confetti-fall 2.6s linear forwards",
        "confetti-spin": "confetti-spin 2.6s linear infinite",
      },
    },
  },
  plugins: [],
};
